[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp[speedups]>=3.12.15",
    "duckdb>=1.3.2",
    "jupyterlab>=4.4.6",
    "polars>=1.32.3",
    "pydantic>=2.11.7",
]
